### ISSUE TITLE
Alignment of title page

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/thesis_latex_template#1]
it seems that the title page's logos and supervisor, nr. and filling data information are not well aligned, in particular the left margin seems smaller than the right one. I would expect a symmetrical left/right margin distribution.

![grafik](https://github.com/upb-lea/thesis_latex_template/assets/56304296/85cedd65-29a2-48fe-b114-184312708403)

**Comment by kss-lea** [comment]
Updated the class definition. Should be OK now. Please verify!

**Comment by wallscheid** [comment]
verified and looks good, thanks!
