### ISSUE TITLE
Glossary, acronyms and nomenclature are not compiled/shown in Overleaf

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/thesis_latex_template#2]
They can be found with the TOC 
![grafik](https://github.com/upb-lea/thesis_latex_template/assets/56304296/7feb3b52-4ebb-4851-bdd0-3ddf67e2992b)

however, the actual content is not generated within the produced pdf (at least not in Overleaf)
![grafik](https://github.com/upb-lea/thesis_latex_template/assets/56304296/0daea4b6-9a65-4d6f-9b9c-13dfe01191bb)

**Comment by kss-lea** [comment]
As written in the Readme you have to use the release-ZIP for importing into overleaf. Taking the whole repo code creates a subfolder with the project files which at least the index makers cannot handle in overleaf.

If you see this directory structure you have the wrong one:
![grafik](https://github.com/upb-lea/thesis_latex_template/assets/62591617/14224587-1833-4f75-96e9-08249108afe0)


The directory structure must look like this:
![grafik](https://github.com/upb-lea/thesis_latex_template/assets/62591617/50bd32a5-8f78-48f3-a1fd-02dcc4d0064d)

**Comment by wallscheid** [comment]
Yep, ok, that was the issue :)
